version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - docker-image:
          requires:
            - build

executors:
  build:
    working_directory: ~/mimimi
    docker:
      - image: circleci/golang:1.11
  docker-image:
    working_directory: ~/mimimi
    machine:
      enabled: true

jobs:

  build:
    executor: build
    steps:
      - checkout
      - run: make
      - run: make test
      - run: make lint
      - run: make build-static
      - persist_to_workspace:
          root: ~/mimimi
          paths:
            - .

  docker-image:
    executor: docker-image
    steps:
      - attach_workspace:
          at: ~/mimimi
      - run: make docker-build
